name             'cookbooks/deep'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cookbooks/deep'
long_description 'Installs/Configures cookbooks/deep'
version          '0.1.0'
